-- Semantic icon set for the canvas UI.
--
-- Primary source: monochrome SVG assets in assets/ (generated by
-- tools/gen_assets.lua; 24x24, 2px black strokes). They are rasterized at
-- EXACT size by ImageWidget's NanoSVG renderer (ui/primitives.lua handles
-- the SVG/is_icon plumbing) and re-colored for dark surfaces via the invert
-- trick ported from ZenPM: black ink inverted becomes white on pills/theme.
--
-- Fallback: glyphs from KOReader's bundled Nerd Font Symbols font
-- (fonts/nerdfonts/symbols.ttf), kept for icon names without an SVG asset.
-- Glyph ink renders ~1.9x the requested font size, which is why SVG assets
-- are drawn at ICON_SCALE x size: call-site geometry (bars, pills, badges)
-- was tuned against that visual size, so keeping it means every caller gets
-- crisp vectors with zero layout churn.
--
-- Color semantics: SVG icons always paint in ink (like ZenPM). Passing
-- color = Theme.muted dims them (lighten on light theme, darken on inverted)
-- instead; other colors are honored only by the glyph fallback.

local Constants = require("kt_constants")
local P = require("ktui/primitives")
local Font = require("ui/font")
local Theme = require("ktui/theme")

local Icons = {}

local ICON_SCALE = 2
local ASSET_DIR = Constants.PLUGIN_DIR .. "/assets"

-- name -> FontAwesome codepoint (glyph fallback only)
local map = {
    home = 0xf015,
    search = 0xf002,
    sort = 0xf0dc,
    filter = 0xf0b0,
    grid = 0xf009,
    list = 0xf0c9,
    bars = 0xf0c9,
    plus = 0xf067,
    download = 0xf019,
    upload = 0xf093,
    trash = 0xf1f8,
    edit = 0xf044,
    star = 0xf005,
    ["star-empty"] = 0xf006,
    user = 0xf007,
    comments = 0xf086,
    plug = 0xf1e6,
    cog = 0xf013,
    ["chev-left"]=0xf053,
    ["chev-right"]=0xf054,
    ["chev-up"]=0xf077,
    times = 0xf00d,
    check = 0xf00c,
    ["ellipsis-v"]=0xf142,
    copy = 0xf0c5,
    eye = 0xf06e,
    tag = 0xf02b,
    random = 0xf074,
    ban = 0xf05e,
    bookmark = 0xf02e,
    swap = 0xf0ec,
    forward = 0xf04b,
    wrench = 0xf0ad,
    refresh = 0xf021,
    save = 0xf0c7,
    folder = 0xf07b,
    file = 0xf15b,
    clock = 0xf017,
    heart = 0xf004,
    back = 0xf060,
    forward = 0xf061,
    ["chev-down"]=0xf078,
    ["double-chev-right"]=0xf101,
    ["double-chev-left"]=0xf100,
    chat = 0xf075,
    inbox = 0xf01c,
    bolt = 0xf0e7,
    camera = 0xf030,
    image = 0xf03e,
    ["question-circle"]=0xf059,
    ["info-circle"]=0xf05a,
    ["exclamation-triangle"]=0xf071,
    ["arrow-up"]=0xf062,
    ["arrow-down"]=0xf063,
    ["arrow-left"]=0xf060,
    ["arrow-right"]=0xf061,
    ["angle-double-up"]=0xf102,
    ["angle-double-down"]=0xf103,
    music = 0xf001,
    paw = 0xf1b0,
    heartbeat = 0xf21e,
    book = 0xf02d,
    graduation = 0xf19d,
    flame = 0xf06d,
    magic = 0xf0d0,
    sliders = 0xf1de,
    ["window-maximize"]=0xf2d0,
    ["window-restore"]=0xf2d2,
}

local faces = {}

-- Encode a PUA codepoint (U+E000-U+FFFF) as UTF-8.
function Icons.glyph(name)
    local cp = map[name]
    if not cp then
        return ""
    end
    return string.char(0xE0 + math.floor(cp / 0x1000),
        0x80 + math.floor(cp / 0x40) % 0x40,
        0x80 + cp % 0x40)
end

local function face(size)
    local f = faces[size]
    if not f then
        f = Font:getFace("nerdfonts/symbols.ttf", size)
        faces[size] = f
    end
    return f
end

-- Asset lookup cached per name (io.open on every paint would be wasteful;
-- the plugin's assets never change at runtime).
local asset_ok = {}
local function asset_path(name)
    if asset_ok[name] == nil then
        local f = io.open(ASSET_DIR .. "/" .. tostring(name) .. ".svg", "rb")
        asset_ok[name] = (f ~= nil)
        if f then f:close() end
    end
    if asset_ok[name] then
        return ASSET_DIR .. "/" .. name .. ".svg"
    end
    return nil
end

function Icons.has_asset(name)
    return asset_path(name) ~= nil
end

-- Invert black ink on dark surfaces: explicit opts.invert wins, otherwise
-- the inverted theme flips every icon (page background is black there).
local function want_invert(opts)
    if opts and opts.invert ~= nil then
        return opts.invert
    end
    return Theme.get_theme() == "inverted"
end

-- Muted icon over a near-background surface: lighten on the light theme,
-- darken on the inverted one (the reverse would leave a visible box).
local function dim_icon(bb, x, y, s)
    if Theme.get_theme() == "inverted" and bb.darkenRect then
        pcall(function() bb:darkenRect(x, y, s, s, 0.45) end)
    else
        P.dim(bb, x, y, s, s, 0.45)
    end
end

-- Blitbuffer colors are cdata whose __eq assumes both operands are full
-- color instances. LuaJIT even routes `cdata ~= nil` through __eq (crash:
-- "attempt to index local 'color'"), so NEVER compare colors to nil.
-- Callers pass the Theme.muted constant itself: guard with type() (which
-- never triggers metamethods) and compare identity with rawequal.
local function is_muted(color)
    return type(color) == "cdata" and rawequal(color, Theme.muted)
end

-- Draw an icon of roughly `size` px, anchored at top-left.
-- Returns the drawn size (width, height).
function Icons.draw(bb, name, x, y, size, opts)
    opts = opts or {}
    local file = asset_path(name)
    if file then
        local s = size * ICON_SCALE
        local ok = P.image(bb, file, x, y, s, s, {
            is_icon = true,
            invert = want_invert(opts),
        })
        if ok then
            if is_muted(opts.color) then
                dim_icon(bb, x, y, s)
            end
            return { w = s, h = s }
        end
        -- fall through to glyphs if rasterization failed
    end
    return P.text(bb, Icons.glyph(name), x, y, size * 2, nil, {
        face = face(size),
        color = opts.color or Theme.ink,
    })
end

-- Measure an icon at the given font size.
function Icons.text_size(name, size)
    if asset_path(name) then
        return { w = size * ICON_SCALE, h = size * ICON_SCALE }
    end
    return P.text_size(Icons.glyph(name), size * 2, nil, {
        face = face(size),
    })
end

-- Draw an icon centered inside a w×h box at (x, y).
function Icons.center(bb, name, x, y, w, h, size, opts)
    size = size or math.floor(math.min(w, h) * 0.6)
    local s = Icons.text_size(name, size)
    Icons.draw(bb, name, x + math.floor((w - s.w) / 2), y + math.floor((h - s.h) / 2), size, opts)
end

-- Inline label for native ButtonDialog rows: glyph + space padding so the
-- text column aligns across rows (our own take on ZenPM's inline_icon_map,
-- using our glyph map). Measured once, cached. Text-only fallback when the
-- name has no glyph.
local inline_pad_cache
function Icons.inline_label(name, text)
    local glyph = Icons.glyph(name)
    text = tostring(text or "")
    if glyph == "" then
        return text
    end
    local f = face(20)
    if not inline_pad_cache then
        local space_w = P.text_size(" ", 1024, nil, { face = f }).w
        local max_w = 0
        for key in pairs(map) do
            local g = Icons.glyph(key)
            if g ~= "" then
                local w = P.text_size(g, 1024, nil, { face = f }).w
                if w > max_w then max_w = w end
            end
        end
        inline_pad_cache = { space = space_w, max = max_w }
    end
    local gw = P.text_size(glyph, 1024, nil, { face = f }).w
    local pad_n = math.ceil((inline_pad_cache.max - gw) / math.max(1, inline_pad_cache.space))
    return glyph .. string.rep(" ", pad_n + 2) .. text
end

return Icons
