local WidgetContainer = require("ui/widget/container/widgetcontainer")
local _ = require("gettext")
local Launcher = require("kt_launcher")

local Constants = require("kt_constants")

local KOTavern = WidgetContainer:extend{
    name = "kotavern",
    is_doc_only = false,
}

-- Register our bundled (subset) Nerd Font so glyph icons are deterministic
-- across devices and any glyph missing from KOReader's own symbols.ttf still
-- resolves (it joins the global fallback chain). Same mechanism ZenPM uses.
-- The font is generated by tools/subset_nerd_font.sh (pyftsubset).
--
-- Nerd fonts can NOT be registered in crengine (cre.registerFont fails even
-- for KOReader's own fonts/nerdfonts/symbols.ttf - credocument.lua skips them
-- by matching "/nerdfonts/symbols.ttf" in the fontlist path). Bundling ours
-- under fonts/nerdfonts/symbols.ttf makes engineInit skip it too, so no boot
-- "failed to register crengine font" error; it stays usable by the canvas
-- glyph fallback (Font.fallbacks entries are matched as substrings of
-- fontlist paths, so a unique suffix avoids clashing with the real symbols.ttf).
local function register_nerd_font()
    local font_path = Constants.PLUGIN_DIR .. "/fonts/nerdfonts/symbols.ttf"
    local fallback_name = "kotavern.koplugin/fonts/nerdfonts/symbols.ttf"
    if not require("util").pathExists(font_path) then
        return
    end
    local Font = require("ui/font")
    local FontList = require("fontlist")
    FontList:getFontList()
    for _, path in ipairs(FontList.fontlist) do
        if path == font_path then
            font_path = nil
            break
        end
    end
    if font_path then
        table.insert(FontList.fontlist, font_path)
    end
    for _, fallback in ipairs(Font.fallbacks) do
        if fallback == fallback_name then return end
    end
    table.insert(Font.fallbacks, fallback_name)
end

function KOTavern:init()
    pcall(register_nerd_font)
    -- Register in KOReader's main menu
    self.ui.menu:registerToMainMenu(self)
end

function KOTavern:addToMainMenu(menu_items)
    menu_items.kotavern = {
        text = _("KOTavern"),
        -- No sorting_hint: first menu like ZenPM. new = true skips the NEW
        -- badge the sorter would otherwise prepend (user request).
        new = true,
        callback = function()
            Launcher.open(self)
        end,
    }
end

function KOTavern:onKOTavernOpen()
    Launcher.open(self)
end

function KOTavern:onCloseWidget()
    -- Cleanup if needed
end

return KOTavern
